import { INPUT_SYMBOL_IDS } from '@/engine/tables/inputSymbolTable'

type PrimitiveEntry = {
  char: string
  sequence: number[]
}

export const PRIMITIVE_INITIALS: PrimitiveEntry[] = [
  { char: 'ᄀ', sequence: [INPUT_SYMBOL_IDS.GIYEOK] },
  { char: 'ᄁ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_GIYEOK] },
  { char: 'ᄂ', sequence: [INPUT_SYMBOL_IDS.NIEUN] },
  { char: 'ᄔ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_NIEUN] },
  { char: 'ᄃ', sequence: [INPUT_SYMBOL_IDS.DIGEUT] },
  { char: 'ᄄ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_DIGEUT] },
  { char: 'ᄅ', sequence: [INPUT_SYMBOL_IDS.RIEUL] },
  { char: 'ᄙ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_RIEUL] },
  { char: 'ᄆ', sequence: [INPUT_SYMBOL_IDS.MIEUM] },
  { char: 'ᄇ', sequence: [INPUT_SYMBOL_IDS.BIEUP] },
  { char: 'ᄈ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_BIEUP] },
  { char: 'ᄉ', sequence: [INPUT_SYMBOL_IDS.SIOS] },
  { char: 'ᄊ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SIOS] },
  { char: 'ᄼ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SIOS] },
  { char: 'ᄽ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SSANGSIOS] },
  { char: 'ᄾ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SIOS] },
  { char: 'ᄿ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGSIOS] },
  { char: 'ᄋ', sequence: [INPUT_SYMBOL_IDS.IEUNG] },
  { char: 'ᅌ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_OLD_IEUNG] },
  { char: 'ᅇ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_IEUNG] },
  { char: 'ᄌ', sequence: [INPUT_SYMBOL_IDS.CIEUC] },
  { char: 'ᄍ', sequence: [INPUT_SYMBOL_IDS.SSANGCIEUC] },
  { char: 'ᅎ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_CIEUC] },
  { char: 'ᅏ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SSANGCIEUC] },
  { char: 'ᅐ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_CIEUC] },
  { char: 'ᅑ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGCIEUC] },
  { char: 'ᅀ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_BANCHIEUM] },
  { char: 'ᄎ', sequence: [INPUT_SYMBOL_IDS.CHIEUCH] },
  { char: 'ᅔ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_CHIEUCH] },
  { char: 'ᅕ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_CHIEUCH] },
  { char: 'ᄏ', sequence: [INPUT_SYMBOL_IDS.KHIEUKH] },
  { char: 'ᄐ', sequence: [INPUT_SYMBOL_IDS.THIEUTH] },
  { char: 'ꥹ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_THIEUTH] },
  { char: 'ᄑ', sequence: [INPUT_SYMBOL_IDS.PHIEUPH] },
  { char: 'ᄒ', sequence: [INPUT_SYMBOL_IDS.HIEUH] },
  { char: 'ᅘ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_HIEUH] },
  { char: 'ᅙ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_YEORINHIEUH] },
  { char: 'ꥼ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_YEORINHIEUH] },
  { char: 'ᅟ', sequence: [INPUT_SYMBOL_IDS.CHOSEONG_FILLER] },
]

export const PRIMITIVE_MEDIALS: PrimitiveEntry[] = [
  { char: 'ᅡ', sequence: [INPUT_SYMBOL_IDS.A] },
  { char: 'ᅢ', sequence: [INPUT_SYMBOL_IDS.AE] },
  { char: 'ᅣ', sequence: [INPUT_SYMBOL_IDS.YA] },
  { char: 'ᅤ', sequence: [INPUT_SYMBOL_IDS.YAE] },
  { char: 'ᅥ', sequence: [INPUT_SYMBOL_IDS.EO] },
  { char: 'ᅦ', sequence: [INPUT_SYMBOL_IDS.E] },
  { char: 'ᅧ', sequence: [INPUT_SYMBOL_IDS.YEO] },
  { char: 'ᅨ', sequence: [INPUT_SYMBOL_IDS.YE] },
  { char: 'ᅩ', sequence: [INPUT_SYMBOL_IDS.O] },
  { char: 'ᅭ', sequence: [INPUT_SYMBOL_IDS.YO] },
  { char: 'ᅮ', sequence: [INPUT_SYMBOL_IDS.U] },
  { char: 'ᅲ', sequence: [INPUT_SYMBOL_IDS.YU] },
  { char: 'ᅳ', sequence: [INPUT_SYMBOL_IDS.EU] },
  { char: 'ᅵ', sequence: [INPUT_SYMBOL_IDS.I] },
  { char: 'ᆞ', sequence: [INPUT_SYMBOL_IDS.ARAEA] },
  { char: 'ᆢ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SSANGARAEA] },
  { char: 'ᆂ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_O] },
  { char: 'ᆍ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_U] },
  { char: 'ᆖ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_EU] },
  { char: 'ퟄ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_I] },
  { char: 'ᅠ', sequence: [INPUT_SYMBOL_IDS.JUNGSEONG_FILLER] },
]

export const PRIMITIVE_FINALS: PrimitiveEntry[] = [
  { char: 'ᆧ', sequence: [INPUT_SYMBOL_IDS.DIRECT_FINAL_U_11A7] },
  { char: 'ᆨ', sequence: [INPUT_SYMBOL_IDS.GIYEOK] },
  { char: 'ᆩ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_GIYEOK] },
  { char: 'ᆫ', sequence: [INPUT_SYMBOL_IDS.NIEUN] },
  { char: 'ᆮ', sequence: [INPUT_SYMBOL_IDS.DIGEUT] },
  { char: 'ᆯ', sequence: [INPUT_SYMBOL_IDS.RIEUL] },
  { char: 'ᆷ', sequence: [INPUT_SYMBOL_IDS.MIEUM] },
  { char: 'ퟠ', sequence: [INPUT_SYMBOL_IDS.SHIFT_MIEUM] },
  { char: 'ᆸ', sequence: [INPUT_SYMBOL_IDS.BIEUP] },
  { char: 'ᆺ', sequence: [INPUT_SYMBOL_IDS.SIOS] },
  { char: 'ᆻ', sequence: [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SIOS] },
  { char: 'ᇫ', sequence: [INPUT_SYMBOL_IDS.DIRECT_FINAL_U_11EB] },
  { char: 'ᆼ', sequence: [INPUT_SYMBOL_IDS.IEUNG] },
  { char: 'ᇰ', sequence: [INPUT_SYMBOL_IDS.DIRECT_FINAL_U_11F0] },
  { char: 'ᆽ', sequence: [INPUT_SYMBOL_IDS.CIEUC] },
  { char: 'ᆾ', sequence: [INPUT_SYMBOL_IDS.CHIEUCH] },
  { char: 'ᆿ', sequence: [INPUT_SYMBOL_IDS.KHIEUKH] },
  { char: 'ᇀ', sequence: [INPUT_SYMBOL_IDS.THIEUTH] },
  { char: 'ᇁ', sequence: [INPUT_SYMBOL_IDS.PHIEUPH] },
  { char: 'ᇂ', sequence: [INPUT_SYMBOL_IDS.HIEUH] },
  { char: 'ᇹ', sequence: [INPUT_SYMBOL_IDS.DIRECT_FINAL_U_11F9] },
]
