import type { InputSymbolId, JamoId } from '@/engine/core/types'
import {
  ARCHAIC_FINAL_RULES,
  ARCHAIC_INITIAL_RULES,
  ARCHAIC_MEDIAL_RULES,
} from '@/engine/tables/archaicRuleCatalog'
import { BASE_FINAL_TARGET_CHARS, BASE_INITIAL_TARGET_CHARS, BASE_MEDIAL_TARGET_CHARS } from '@/engine/tables/baseInventoryCoverage'
import { INPUT_SYMBOL_IDS } from '@/engine/tables/inputSymbolTable'
import type { InventoryEntry } from '@/engine/tables/inventoryCatalog'
import { TARGET_INVENTORY, toInventorySymbolName } from '@/engine/tables/inventoryCatalog'
import { JAMO_IDS, JAMO_UNICODE_TABLE } from '@/engine/tables/jamoTable'

type SimpleMappingEntry = readonly [InputSymbolId, JamoId]
type ClusterMappingEntry = readonly [readonly InputSymbolId[], JamoId]

function createKey(ids: readonly InputSymbolId[]) {
  return ids.join(',')
}

function createSimpleMapping(entries: readonly SimpleMappingEntry[]) {
  return Object.fromEntries(entries) as Record<number, JamoId>
}

function createClusterMap(entries: readonly ClusterMappingEntry[]) {
  return new Map(entries.map(([ids, jamoId]) => [createKey(ids), jamoId]))
}

function inventoryInputId(entry: InventoryEntry) {
  return INPUT_SYMBOL_IDS[toInventorySymbolName(entry)]
}

function inventoryJamoId(entry: InventoryEntry) {
  return JAMO_IDS[toInventorySymbolName(entry) as keyof typeof JAMO_IDS]
}

function jamoIdFromChar(char: string) {
  return JAMO_UNICODE_TABLE.indexOf(char as (typeof JAMO_UNICODE_TABLE)[number])
}

const SIMPLE_INITIAL_ENTRIES = [
  // 초성: 한글 순
  [INPUT_SYMBOL_IDS.GIYEOK, JAMO_IDS.CHOSEONG_GIYEOK],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_GIYEOK, JAMO_IDS.CHOSEONG_SSANGGIYEOK],
  [INPUT_SYMBOL_IDS.NIEUN, JAMO_IDS.CHOSEONG_NIEUN],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_NIEUN, JAMO_IDS.CHOSEONG_SSANGNIEUN],
  [INPUT_SYMBOL_IDS.DIGEUT, JAMO_IDS.CHOSEONG_DIGEUT],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_DIGEUT, JAMO_IDS.CHOSEONG_SSANGDIGEUT],
  [INPUT_SYMBOL_IDS.RIEUL, JAMO_IDS.CHOSEONG_RIEUL],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_RIEUL, JAMO_IDS.CHOSEONG_SSANGRIEUL],
  [INPUT_SYMBOL_IDS.MIEUM, JAMO_IDS.CHOSEONG_MIEUM],
  [INPUT_SYMBOL_IDS.BIEUP, JAMO_IDS.CHOSEONG_BIEUP],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_BIEUP, JAMO_IDS.CHOSEONG_SSANGBIEUP],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_PIEUP_SIOS_GIYEOK, JAMO_IDS.CHOSEONG_PIEUP_SIOS_GIYEOK],
  [INPUT_SYMBOL_IDS.SIOS, JAMO_IDS.CHOSEONG_SIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SIOS, JAMO_IDS.CHOSEONG_SSANGSIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SIOS, JAMO_IDS.CHOSEONG_CHIDUEUM_SIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SSANGSIOS, JAMO_IDS.CHOSEONG_CHIDUEUM_SSANGSIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SIOS, JAMO_IDS.CHOSEONG_JEONGCHIEUM_SIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGSIOS, JAMO_IDS.CHOSEONG_JEONGCHIEUM_SSANGSIOS],
  [INPUT_SYMBOL_IDS.IEUNG, JAMO_IDS.CHOSEONG_IEUNG],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_OLD_IEUNG, JAMO_IDS.CHOSEONG_OLD_IEUNG],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_IEUNG, JAMO_IDS.CHOSEONG_SSANGIEUNG],
  [INPUT_SYMBOL_IDS.CIEUC, JAMO_IDS.CHOSEONG_CIEUC],
  [INPUT_SYMBOL_IDS.SSANGCIEUC, JAMO_IDS.CHOSEONG_SSANGCIEUC],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_CIEUC, JAMO_IDS.CHOSEONG_CHIDUEUM_CIEUC],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_SSANGCIEUC, JAMO_IDS.CHOSEONG_CHIDUEUM_SSANGCIEUC],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_CIEUC, JAMO_IDS.CHOSEONG_JEONGCHIEUM_CIEUC],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGCIEUC, JAMO_IDS.CHOSEONG_JEONGCHIEUM_SSANGCIEUC],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_BANCHIEUM, JAMO_IDS.CHOSEONG_BANCHIEUM],
  [INPUT_SYMBOL_IDS.CHIEUCH, JAMO_IDS.CHOSEONG_CHIEUCH],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_CHIDUEUM_CHIEUCH, JAMO_IDS.CHOSEONG_CHIDUEUM_CHIEUCH],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_JEONGCHIEUM_CHIEUCH, JAMO_IDS.CHOSEONG_JEONGCHIEUM_CHIEUCH],
  [INPUT_SYMBOL_IDS.KHIEUKH, JAMO_IDS.CHOSEONG_KHIEUKH],
  [INPUT_SYMBOL_IDS.THIEUTH, JAMO_IDS.CHOSEONG_THIEUTH],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_THIEUTH, JAMO_IDS.CHOSEONG_SSANGTHIEUTH],
  [INPUT_SYMBOL_IDS.PHIEUPH, JAMO_IDS.CHOSEONG_PHIEUPH],
  [INPUT_SYMBOL_IDS.HIEUH, JAMO_IDS.CHOSEONG_HIEUH],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_HIEUH, JAMO_IDS.CHOSEONG_SSANGHIEUH],
  [INPUT_SYMBOL_IDS.SPECIAL_CHOSEONG_YEORINHIEUH, JAMO_IDS.CHOSEONG_YEORINHIEUH],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_YEORINHIEUH, JAMO_IDS.CHOSEONG_SSANGYEORINHIEUH],
  [INPUT_SYMBOL_IDS.CHOSEONG_FILLER, JAMO_IDS.CHOSEONG_FILLER],
  ...TARGET_INVENTORY.initial
    .filter((entry) => !BASE_INITIAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      inventoryInputId(entry),
      inventoryJamoId(entry),
    ] as const),
] as const satisfies readonly SimpleMappingEntry[]

const SIMPLE_MEDIAL_ENTRIES = [
  // 중성: 한글 순
  [INPUT_SYMBOL_IDS.A, JAMO_IDS.JUNGSEONG_A],
  [INPUT_SYMBOL_IDS.AE, JAMO_IDS.JUNGSEONG_AE],
  [INPUT_SYMBOL_IDS.YA, JAMO_IDS.JUNGSEONG_YA],
  [INPUT_SYMBOL_IDS.YAE, JAMO_IDS.JUNGSEONG_YAE],
  [INPUT_SYMBOL_IDS.EO, JAMO_IDS.JUNGSEONG_EO],
  [INPUT_SYMBOL_IDS.E, JAMO_IDS.JUNGSEONG_E],
  [INPUT_SYMBOL_IDS.YEO, JAMO_IDS.JUNGSEONG_YEO],
  [INPUT_SYMBOL_IDS.YE, JAMO_IDS.JUNGSEONG_YE],
  [INPUT_SYMBOL_IDS.O, JAMO_IDS.JUNGSEONG_O],
  [INPUT_SYMBOL_IDS.YO, JAMO_IDS.JUNGSEONG_YO],
  [INPUT_SYMBOL_IDS.U, JAMO_IDS.JUNGSEONG_U],
  [INPUT_SYMBOL_IDS.YU, JAMO_IDS.JUNGSEONG_YU],
  [INPUT_SYMBOL_IDS.EU, JAMO_IDS.JUNGSEONG_EU],
  [INPUT_SYMBOL_IDS.I, JAMO_IDS.JUNGSEONG_I],
  [INPUT_SYMBOL_IDS.ARAEA, JAMO_IDS.JUNGSEONG_ARAEA],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SSANGARAEA, JAMO_IDS.JUNGSEONG_SSANGARAEA],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_O, JAMO_IDS.JUNGSEONG_O_O],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_U, JAMO_IDS.JUNGSEONG_U_U],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_EU, JAMO_IDS.JUNGSEONG_EU_EU],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_I, JAMO_IDS.JUNGSEONG_I_I],
  [INPUT_SYMBOL_IDS.SPECIAL_JUNGSEONG_YU_A, JAMO_IDS.JUNGSEONG_YU_A],
  [INPUT_SYMBOL_IDS.SPECIAL_JUNGSEONG_I_YA, JAMO_IDS.JUNGSEONG_I_YA],
  [INPUT_SYMBOL_IDS.JUNGSEONG_FILLER, JAMO_IDS.JUNGSEONG_FILLER],
  ...TARGET_INVENTORY.medial
    .filter((entry) => !BASE_MEDIAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      inventoryInputId(entry),
      inventoryJamoId(entry),
    ] as const),
] as const satisfies readonly SimpleMappingEntry[]

const SIMPLE_FINAL_ENTRIES = [
  // 종성: 한글 순
  [INPUT_SYMBOL_IDS.GIYEOK, JAMO_IDS.JONGSEONG_GIYEOK],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_GIYEOK, JAMO_IDS.JONGSEONG_SSANGGIYEOK],
  [INPUT_SYMBOL_IDS.NIEUN, JAMO_IDS.JONGSEONG_NIEUN],
  [INPUT_SYMBOL_IDS.DIGEUT, JAMO_IDS.JONGSEONG_DIGEUT],
  [INPUT_SYMBOL_IDS.RIEUL, JAMO_IDS.JONGSEONG_RIEUL],
  [INPUT_SYMBOL_IDS.MIEUM, JAMO_IDS.JONGSEONG_MIEUM],
  [INPUT_SYMBOL_IDS.SHIFT_MIEUM, JAMO_IDS.JONGSEONG_SSANGMIEUM],
  [INPUT_SYMBOL_IDS.BIEUP, JAMO_IDS.JONGSEONG_BIEUP],
  [INPUT_SYMBOL_IDS.SIOS, JAMO_IDS.JONGSEONG_SIOS],
  [INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SIOS, JAMO_IDS.JONGSEONG_SSANGSIOS],
  [INPUT_SYMBOL_IDS.IEUNG, JAMO_IDS.JONGSEONG_IEUNG],
  [INPUT_SYMBOL_IDS.CIEUC, JAMO_IDS.JONGSEONG_CIEUC],
  [INPUT_SYMBOL_IDS.CHIEUCH, JAMO_IDS.JONGSEONG_CHIEUCH],
  [INPUT_SYMBOL_IDS.KHIEUKH, JAMO_IDS.JONGSEONG_KHIEUKH],
  [INPUT_SYMBOL_IDS.THIEUTH, JAMO_IDS.JONGSEONG_THIEUTH],
  [INPUT_SYMBOL_IDS.PHIEUPH, JAMO_IDS.JONGSEONG_PHIEUPH],
  [INPUT_SYMBOL_IDS.HIEUH, JAMO_IDS.JONGSEONG_HIEUH],
  ...TARGET_INVENTORY.final
    .filter((entry) => !BASE_FINAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      inventoryInputId(entry),
      inventoryJamoId(entry),
    ] as const),
] as const satisfies readonly SimpleMappingEntry[]

const INITIAL_CLUSTER_ENTRIES = [
  // 초성: 한글 순
  [[INPUT_SYMBOL_IDS.GIYEOK], JAMO_IDS.CHOSEONG_GIYEOK],
  [[INPUT_SYMBOL_IDS.NIEUN], JAMO_IDS.CHOSEONG_NIEUN],
  [[INPUT_SYMBOL_IDS.DIGEUT], JAMO_IDS.CHOSEONG_DIGEUT],
  [[INPUT_SYMBOL_IDS.RIEUL], JAMO_IDS.CHOSEONG_RIEUL],
  [[INPUT_SYMBOL_IDS.MIEUM], JAMO_IDS.CHOSEONG_MIEUM],
  [[INPUT_SYMBOL_IDS.BIEUP], JAMO_IDS.CHOSEONG_BIEUP],
  [[INPUT_SYMBOL_IDS.BIEUP, INPUT_SYMBOL_IDS.SIOS, INPUT_SYMBOL_IDS.GIYEOK], JAMO_IDS.CHOSEONG_PIEUP_SIOS_GIYEOK],
  [[INPUT_SYMBOL_IDS.SIOS], JAMO_IDS.CHOSEONG_SIOS],
  [[INPUT_SYMBOL_IDS.IEUNG], JAMO_IDS.CHOSEONG_IEUNG],
  [[INPUT_SYMBOL_IDS.CIEUC], JAMO_IDS.CHOSEONG_CIEUC],
  [[INPUT_SYMBOL_IDS.SSANGCIEUC], JAMO_IDS.CHOSEONG_SSANGCIEUC],
  [[INPUT_SYMBOL_IDS.CHIEUCH], JAMO_IDS.CHOSEONG_CHIEUCH],
  [[INPUT_SYMBOL_IDS.KHIEUKH], JAMO_IDS.CHOSEONG_KHIEUKH],
  [[INPUT_SYMBOL_IDS.THIEUTH], JAMO_IDS.CHOSEONG_THIEUTH],
  [[INPUT_SYMBOL_IDS.PHIEUPH], JAMO_IDS.CHOSEONG_PHIEUPH],
  [[INPUT_SYMBOL_IDS.HIEUH], JAMO_IDS.CHOSEONG_HIEUH],
  ...TARGET_INVENTORY.initial
    .filter((entry) => !BASE_INITIAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      [inventoryInputId(entry)],
      inventoryJamoId(entry),
    ] as const),
  ...ARCHAIC_INITIAL_RULES
    .map((entry) => [entry.sequence, jamoIdFromChar(entry.char)] as const)
    .filter((entry) => entry[1] > 0),
] as const satisfies readonly ClusterMappingEntry[]

const MEDIAL_CLUSTER_ENTRIES = [
  // 중성: 한글 순
  [[INPUT_SYMBOL_IDS.A], JAMO_IDS.JUNGSEONG_A],
  [[INPUT_SYMBOL_IDS.A, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_AE],
  [[INPUT_SYMBOL_IDS.AE], JAMO_IDS.JUNGSEONG_AE],
  [[INPUT_SYMBOL_IDS.YA], JAMO_IDS.JUNGSEONG_YA],
  [[INPUT_SYMBOL_IDS.YA, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_YAE],
  [[INPUT_SYMBOL_IDS.YAE], JAMO_IDS.JUNGSEONG_YAE],
  [[INPUT_SYMBOL_IDS.EO], JAMO_IDS.JUNGSEONG_EO],
  [[INPUT_SYMBOL_IDS.EO, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_E],
  [[INPUT_SYMBOL_IDS.E], JAMO_IDS.JUNGSEONG_E],
  [[INPUT_SYMBOL_IDS.YEO], JAMO_IDS.JUNGSEONG_YEO],
  [[INPUT_SYMBOL_IDS.YEO, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_YE],
  [[INPUT_SYMBOL_IDS.YE], JAMO_IDS.JUNGSEONG_YE],
  [[INPUT_SYMBOL_IDS.O], JAMO_IDS.JUNGSEONG_O],
  [[INPUT_SYMBOL_IDS.O, INPUT_SYMBOL_IDS.A], JAMO_IDS.JUNGSEONG_WA],
  [[INPUT_SYMBOL_IDS.O, INPUT_SYMBOL_IDS.AE], JAMO_IDS.JUNGSEONG_WAE],
  [[INPUT_SYMBOL_IDS.O, INPUT_SYMBOL_IDS.A, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_WAE],
  [[INPUT_SYMBOL_IDS.O, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_OE],
  [[INPUT_SYMBOL_IDS.YO], JAMO_IDS.JUNGSEONG_YO],
  [[INPUT_SYMBOL_IDS.U], JAMO_IDS.JUNGSEONG_U],
  [[INPUT_SYMBOL_IDS.U, INPUT_SYMBOL_IDS.EO], JAMO_IDS.JUNGSEONG_WEO],
  [[INPUT_SYMBOL_IDS.U, INPUT_SYMBOL_IDS.E], JAMO_IDS.JUNGSEONG_WE],
  [[INPUT_SYMBOL_IDS.U, INPUT_SYMBOL_IDS.EO, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_WE],
  [[INPUT_SYMBOL_IDS.U, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_WI],
  [[INPUT_SYMBOL_IDS.YU], JAMO_IDS.JUNGSEONG_YU],
  [[INPUT_SYMBOL_IDS.YU, INPUT_SYMBOL_IDS.A], JAMO_IDS.JUNGSEONG_YU_A],
  [[INPUT_SYMBOL_IDS.EU], JAMO_IDS.JUNGSEONG_EU],
  [[INPUT_SYMBOL_IDS.EU, INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_YI],
  [[INPUT_SYMBOL_IDS.I], JAMO_IDS.JUNGSEONG_I],
  [[INPUT_SYMBOL_IDS.I, INPUT_SYMBOL_IDS.YA], JAMO_IDS.JUNGSEONG_I_YA],
  [[INPUT_SYMBOL_IDS.ARAEA], JAMO_IDS.JUNGSEONG_ARAEA],
  ...TARGET_INVENTORY.medial
    .filter((entry) => !BASE_MEDIAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      [inventoryInputId(entry)],
      inventoryJamoId(entry),
    ] as const),
  ...ARCHAIC_MEDIAL_RULES
    .map((entry) => [entry.sequence, jamoIdFromChar(entry.char)] as const)
    .filter((entry) => entry[1] > 0),
] as const satisfies readonly ClusterMappingEntry[]

const FINAL_CLUSTER_ENTRIES = [
  // 종성: 한글 순
  [[INPUT_SYMBOL_IDS.GIYEOK], JAMO_IDS.JONGSEONG_GIYEOK],
  [[INPUT_SYMBOL_IDS.SPECIAL_SHIFT_GIYEOK], JAMO_IDS.JONGSEONG_SSANGGIYEOK],
  [[INPUT_SYMBOL_IDS.GIYEOK, INPUT_SYMBOL_IDS.SIOS], JAMO_IDS.JONGSEONG_GIYEOK_SIOS],
  [[INPUT_SYMBOL_IDS.NIEUN], JAMO_IDS.JONGSEONG_NIEUN],
  [[INPUT_SYMBOL_IDS.NIEUN, INPUT_SYMBOL_IDS.CIEUC], JAMO_IDS.JONGSEONG_NIEUN_CIEUC],
  [[INPUT_SYMBOL_IDS.NIEUN, INPUT_SYMBOL_IDS.HIEUH], JAMO_IDS.JONGSEONG_NIEUN_HIEUH],
  [[INPUT_SYMBOL_IDS.DIGEUT], JAMO_IDS.JONGSEONG_DIGEUT],
  [[INPUT_SYMBOL_IDS.RIEUL], JAMO_IDS.JONGSEONG_RIEUL],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.GIYEOK], JAMO_IDS.JONGSEONG_RIEUL_GIYEOK],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.MIEUM], JAMO_IDS.JONGSEONG_RIEUL_MIEUM],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.BIEUP], JAMO_IDS.JONGSEONG_RIEUL_BIEUP],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.SIOS], JAMO_IDS.JONGSEONG_RIEUL_SIOS],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.THIEUTH], JAMO_IDS.JONGSEONG_RIEUL_THIEUTH],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.PHIEUPH], JAMO_IDS.JONGSEONG_RIEUL_PHIEUPH],
  [[INPUT_SYMBOL_IDS.RIEUL, INPUT_SYMBOL_IDS.HIEUH], JAMO_IDS.JONGSEONG_RIEUL_HIEUH],
  [[INPUT_SYMBOL_IDS.MIEUM], JAMO_IDS.JONGSEONG_MIEUM],
  [[INPUT_SYMBOL_IDS.BIEUP], JAMO_IDS.JONGSEONG_BIEUP],
  [[INPUT_SYMBOL_IDS.BIEUP, INPUT_SYMBOL_IDS.SIOS], JAMO_IDS.JONGSEONG_BIEUP_SIOS],
  [[INPUT_SYMBOL_IDS.SIOS], JAMO_IDS.JONGSEONG_SIOS],
  [[INPUT_SYMBOL_IDS.SPECIAL_SHIFT_SIOS], JAMO_IDS.JONGSEONG_SSANGSIOS],
  [[INPUT_SYMBOL_IDS.IEUNG], JAMO_IDS.JONGSEONG_IEUNG],
  [[INPUT_SYMBOL_IDS.CIEUC], JAMO_IDS.JONGSEONG_CIEUC],
  [[INPUT_SYMBOL_IDS.CHIEUCH], JAMO_IDS.JONGSEONG_CHIEUCH],
  [[INPUT_SYMBOL_IDS.KHIEUKH], JAMO_IDS.JONGSEONG_KHIEUKH],
  [[INPUT_SYMBOL_IDS.THIEUTH], JAMO_IDS.JONGSEONG_THIEUTH],
  [[INPUT_SYMBOL_IDS.PHIEUPH], JAMO_IDS.JONGSEONG_PHIEUPH],
  [[INPUT_SYMBOL_IDS.HIEUH], JAMO_IDS.JONGSEONG_HIEUH],
  ...TARGET_INVENTORY.final
    .filter((entry) => !BASE_FINAL_TARGET_CHARS.includes(entry.char))
    .map((entry) => [
      [inventoryInputId(entry)],
      inventoryJamoId(entry),
    ] as const),
  ...ARCHAIC_FINAL_RULES
    .map((entry) => [entry.sequence, jamoIdFromChar(entry.char)] as const)
    .filter((entry) => entry[1] > 0),
] as const satisfies readonly ClusterMappingEntry[]

export const SIMPLE_INITIAL_JAMO = createSimpleMapping(SIMPLE_INITIAL_ENTRIES)
export const SIMPLE_MEDIAL_JAMO = createSimpleMapping(SIMPLE_MEDIAL_ENTRIES)
export const SIMPLE_FINAL_JAMO = createSimpleMapping(SIMPLE_FINAL_ENTRIES)

export const INITIAL_CLUSTER_MAP = createClusterMap(INITIAL_CLUSTER_ENTRIES)
export const MEDIAL_CLUSTER_MAP = createClusterMap(MEDIAL_CLUSTER_ENTRIES)
export const FINAL_CLUSTER_MAP = createClusterMap(FINAL_CLUSTER_ENTRIES)

export const SUPPORTED_INITIAL_JAMO_IDS = SIMPLE_INITIAL_ENTRIES.map(([, jamoId]) => jamoId)
export const SUPPORTED_MEDIAL_JAMO_IDS = SIMPLE_MEDIAL_ENTRIES.map(([, jamoId]) => jamoId)
export const SUPPORTED_FINAL_JAMO_IDS = SIMPLE_FINAL_ENTRIES.map(([, jamoId]) => jamoId)
export const DIRECT_INITIAL_SYMBOL_IDS = TARGET_INVENTORY.initial
  .filter((entry) => !BASE_INITIAL_TARGET_CHARS.includes(entry.char))
  .map((entry) => inventoryInputId(entry))
export const DIRECT_MEDIAL_SYMBOL_IDS = TARGET_INVENTORY.medial
  .filter((entry) => !BASE_MEDIAL_TARGET_CHARS.includes(entry.char))
  .map((entry) => inventoryInputId(entry))
export const DIRECT_FINAL_SYMBOL_IDS = TARGET_INVENTORY.final
  .filter((entry) => !BASE_FINAL_TARGET_CHARS.includes(entry.char))
  .map((entry) => inventoryInputId(entry))

export const SUPPORTED_INITIAL_COUNT = SIMPLE_INITIAL_ENTRIES.length
export const SUPPORTED_MEDIAL_COUNT = SIMPLE_MEDIAL_ENTRIES.length
export const SUPPORTED_FINAL_COUNT = SIMPLE_FINAL_ENTRIES.length

export function resolveCluster(
  clusterMap: Map<string, JamoId>,
  inputIds: InputSymbolId[],
) {
  return clusterMap.get(createKey(inputIds))
}
