import { BASE_FINAL_TARGET_CHARS, BASE_INITIAL_TARGET_CHARS, BASE_MEDIAL_TARGET_CHARS } from '@/engine/tables/baseInventoryCoverage'
import { TARGET_INVENTORY, toInventorySymbolName } from '@/engine/tables/inventoryCatalog'

const DIRECT_INITIAL_SYMBOLS = TARGET_INVENTORY.initial
  .filter((entry) => !BASE_INITIAL_TARGET_CHARS.includes(entry.char))
  .map(toInventorySymbolName)

const DIRECT_MEDIAL_SYMBOLS = TARGET_INVENTORY.medial
  .filter((entry) => !BASE_MEDIAL_TARGET_CHARS.includes(entry.char))
  .map(toInventorySymbolName)

const DIRECT_FINAL_SYMBOLS = TARGET_INVENTORY.final
  .filter((entry) => !BASE_FINAL_TARGET_CHARS.includes(entry.char))
  .map(toInventorySymbolName)

export const INPUT_SYMBOL_TABLE = [
  'NONE',

  // 자음: 한글 순
  'GIYEOK',
  'SPECIAL_SHIFT_GIYEOK',
  'NIEUN',
  'SPECIAL_SHIFT_NIEUN',
  'DIGEUT',
  'SPECIAL_SHIFT_DIGEUT',
  'RIEUL',
  'SPECIAL_SHIFT_RIEUL',
  'MIEUM',
  'SHIFT_MIEUM',
  'BIEUP',
  'SPECIAL_SHIFT_BIEUP',
  'SIOS',
  'SPECIAL_SHIFT_SIOS',
  'IEUNG',
  'SPECIAL_SHIFT_IEUNG',
  'CIEUC',
  'SSANGCIEUC',
  'SPECIAL_SHIFT_CIEUC',
  'CHIEUCH',
  'KHIEUKH',
  'THIEUTH',
  'SPECIAL_SHIFT_THIEUTH',
  'PHIEUPH',
  'HIEUH',
  'SPECIAL_SHIFT_HIEUH',
  'SPECIAL_SHIFT_YEORINHIEUH',

  // 옛한글 초성 특수
  'SPECIAL_CHOSEONG_PIEUP_SIOS_GIYEOK',
  'SPECIAL_CHOSEONG_CHIDUEUM_SIOS',
  'SPECIAL_CHOSEONG_CHIDUEUM_SSANGSIOS',
  'SPECIAL_CHOSEONG_JEONGCHIEUM_SIOS',
  'SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGSIOS',
  'SPECIAL_CHOSEONG_OLD_IEUNG',
  'SPECIAL_CHOSEONG_CHIDUEUM_CIEUC',
  'SPECIAL_CHOSEONG_CHIDUEUM_SSANGCIEUC',
  'SPECIAL_CHOSEONG_JEONGCHIEUM_CIEUC',
  'SPECIAL_CHOSEONG_JEONGCHIEUM_SSANGCIEUC',
  'SPECIAL_CHOSEONG_BANCHIEUM',
  'SPECIAL_CHOSEONG_CHIDUEUM_CHIEUCH',
  'SPECIAL_CHOSEONG_JEONGCHIEUM_CHIEUCH',
  'SPECIAL_CHOSEONG_YEORINHIEUH',
  ...DIRECT_INITIAL_SYMBOLS,

  // 모음: 한글 순
  'A',
  'AE',
  'YA',
  'YAE',
  'EO',
  'E',
  'YEO',
  'YE',
  'O',
  'YO',
  'U',
  'YU',
  'EU',
  'I',

  // 옛한글/특수 모음
  'ARAEA',
  'SPECIAL_SHIFT_SSANGARAEA',
  'SPECIAL_SHIFT_O',
  'SPECIAL_SHIFT_U',
  'SPECIAL_SHIFT_EU',
  'SPECIAL_SHIFT_I',
  'SPECIAL_JUNGSEONG_YU_A',
  'SPECIAL_JUNGSEONG_I_YA',
  ...DIRECT_MEDIAL_SYMBOLS,

  // 제어/보조
  ...DIRECT_FINAL_SYMBOLS,
  'CHOSEONG_FILLER',
  'JUNGSEONG_FILLER',
  'SPACE',
  'TONE_SINGLE',
  'TONE_DOUBLE',
  'BACKSPACE',
] as const

export const INPUT_SYMBOL_COUNT = INPUT_SYMBOL_TABLE.length

export const INPUT_SYMBOL_IDS = Object.fromEntries(
  INPUT_SYMBOL_TABLE.map((name, index) => [name, index]),
) as Record<string, number>
